import { chromium } from "playwright"
const b = await chromium.launch()
const p = await (await b.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 3, colorScheme: "dark" })).newPage()
await p.goto("https://briannguyen291.github.io/tecxmath/?cb=" + Date.now(), { waitUntil: "networkidle" })
await p.$$eval(".row:not([disabled])", r => r[0].click())
await p.waitForSelector(".beat")
const s = await p.$('input[type="range"][aria-label="a"]'); await s.focus()
for (let i=0;i<8;i++) await p.keyboard.press("ArrowRight")
await p.evaluate(() => window.scrollBy(0, 300)); await p.waitForTimeout(400)
await p.screenshot({ path: "/tmp/claude-501/-Users-biran/432123e5-8140-42d3-9db2-ec08ec2a4e26/scratchpad/mob-dark.png" })
await b.close()
